### PR TITLE
Feat/event

### PR DESCRIPTION
**Pull request by shoedler**
# Main changes

## Dtos

- Aligned all current frontend dtos to Backend
- Updated all components which depend on dtos
- Added `JsonParseInterceptor` and along with it a `DtoJsonParser` to intercept `HttpResponse`s. Now, some dto props such as dates can be parsed manually by configuring a handler in the `JSON.parse` `reviver` function.

## Services

- Refactored all Frontend Api services to correctly initialize Dtos and convert other responses (ids, objects)
- Added `PlanService` (Api)

## Components

- Added `LazyImageComponent` atom to lazily get external images
- Added `ToggleComponent` atom (Currently used as a slider for `isPrivate` in the plan event stepper)
- Added `VoidComponent` atom to display nice "nothing here"-like hints.
- Added `EventOverviewComponent` to display an overview of a plan. 

## Create Event Feature (plan-event)

- Updated `AutocompleteComponent` to show images (opt-in)
- Added mock game collection
- Finished "plan-event" feature

## Events Overview Feature

- Added `EventCardComponent` to display events (plans) in the events overview
- Finished events overview feature ("landing page" once logged in)

## View Event Feature

- Prepared `ViewEventComponents` for the view event feature

## Misc

- Fixed bug in error handling
- Added `TruncatePipe` to truncate text
- Added date utils to format dates/time to CH format

# To do

Some questions that need to be resolved before moving forward:

- [x] `TODO (decide): Does the backend filter out public plans that have already happened?` $\to$ Currently, **not** handled in the frontend. This should be done in the backend - see the follow up question for an implementation suggestion. @yungxramoz 

@yungxramoz Kann ich im Backend noch implementieren.

- [x] `TODO (decide): Does the backend filter out public plans that are mine?` $\to$ Currently done in the frontend. Could leave it like this. In the frontend I need to iterate over all the public plans to filter out the ones that are mine @yungxramoz. It's faster to do this in the backend, but I need to iterate the public plans anyway to resolve the next ToDo:

@yungxramoz Kann ich im Backend implementieren, dann ist es konsistent da gehandlet und nicht gemischt gefiltert.

- [x] `TODO (decide): How do we handle events that have been joined? Currently, there's no overview of them` $\to$ Best way imo would propbably be to have a `api/plans/joined` endpoint to retrieve the list of current gatherings for `me`. This would allow iterating the public events and marking an event-card with some sort of icon if it has been joined already. @yungxramoz 

@yungxramoz Ist eine coole Idee, ich würde dies aber vermutlich als Stretch Item nehmen wenn wir genügend Zeit haben da es keine Anforderung ist. Du kannst es dir wie in einem Doodle vorstellen, da hast du einfach über den Link Zugriff drauf.

- [x] `TODO (decide): How do we push the selected gatherings to the backend after selecting dates?` $\to$ There were already discussions about this, but it seems that nothing has been implemented yet. I'd suggest using a `createOrUpdateSelectedGatheringsForPlan({ planId, selectedGatherings })` endpoint in `GatheringResource` where the frontend will provide a `planId` and a list of selected gathering dates. The backend will create these gatherings for the current user if they don't exist already. If the POST request happens again, the backend will delete current gatherings for this plan if they are not in the request body and - like before - create new ones. Alongside this endpoint we'd probably need an additional endpoint to `getSelectedGatheringsOfPlan(planId)` for the current user.

@yungxramoz Ich werde das beim Gathering Feature so umsetzen.

## Follow up question

**What's the point of selecting gatherings anyway?** Currently there is no way for an event author to decide on one of the proposed dates. $\to$ We probably require some sort of state-field on the `PlanEntity` e.g
-  `CREATED`: Users can select/enroll for one of the plans gatherings,
-  `DECIDED`: Users cannot enroll anymore (Or maybe they can, but just on the decided date, as long as the playerlimit is not reached). These plans are still displayed in the overview
- `FINISHED`: Event has already happened - these plans do not get fetched by the backend and therefore are not displayed in the frontend.

@yungxramoz Es gibt keine Anforderung bezüglich Status oder das eine Entscheidung getroffen werden muss. Auch hier kannst du es dir wie eine Doodle Umfrage vorstellen. Wir nutzen dann den Kommentar Bereich um den Termin zu fixen. Aber coole Idee und das kann ich nach der Projektarbeit umsetzen.

Maybe a state field is too much - but a pragmatic solution would be to have an additional nullable field `decidedGathering` on the `PlanEntity`. The backend (and frontend) would then be able to determine the "state" of any plan via it's properties.
- `decidedGathering` == null $\to$ Essentially is the "CREATED" state where users can still join
- `decidedGathering != null & it's date < now()` $\to$ Represents the `DECIDED` state
- `decidedGathering != null & it's date > now()` $\to$ Represents the `FINISHED` state.

### CODE REVIEW

**Comment by yungxramoz** [comment]
Wenn die Punkte von @Raemy92 gefixt sind passt das für mich.

**Comment by shoedler** [comment]
@Raemy92 @yungxramoz 
> Bei den einzelnen Schritten sollten noch Previous und Next Buttons unten hin
$\to$ Ist nun drin

> Bei Summary Options den Tag auch in die Auflistung
$\to$ Da weiss ich nicht genau was du meinst

> * Event Detail View fehlt noch ein Back Button
$\to$ das tg Icon oben links ist der Back Button

**Comment by yungxramoz** [comment]
@shoedler Ich glaube Laurent meint nicht die Summary sondern beim Event Detail, siehst du keine Gatherings. Auch als Ersteller musst du die Checkboxes für die Daten haben. Wäre wohl logisch das der Organisator an jedem Tag könnte aber da würde ich keinen extra Aufwand betreiben sondern einfach die gleiche Maske anzeigen.

**Comment by shoedler** [comment]
Check, merci @yungxramoz 
@Raemy92, das "View Event" ist nur vorbereitet und ist noch nicht fertig - siehe PR Description ;)

**Review by yungxramoz — DISMISSED** [review]

**Review by yungxramoz — APPROVED** [review]

**Comment by Raemy92** [comment]
@yungxramoz @shoedler ich meinte die Summary beim Erstellen eines Events:
image

Da fände ich es noch praktisch, wenn der Wochentag stehen würde aber ist absolut Tüpfli gschisse ;)

**Pull request merged**
