### PR TITLE
Attend Event

### PR DESCRIPTION
**Pull request by shoedler**
- Connects attending an event to the backend
- Retrieves attending players from the backend
- Added new `OverviewGatheringDto`, used in `OverviewPlanDto` in favor of `LocalDate`
- Added filtering of Gatherings in `findAllAttending` (at `PlanService`) to only include Gatherings that the user is attending
- Updated UI components accordingly
- Refactored some UI Tests to retrieve names from prototype
- Added UI `GatheringService`

### CODE REVIEW

**Comment by yungxramoz** [comment]
Backend passt.

**Comment by shoedler** [comment]
@Raemy92 Ha no ä chlyne Fix dri gno für z search icon im search-input

Neu:
image
image

Alt:
image
image

**Review by Raemy92 — APPROVED** [review]
Vielleicht noch canAttend standardmässig auf false setzen, damit nicht null ans Backend geschickt wird und so eine potenzielle Fehlerquelle schafft. Ansonsten passts, good job!

image

**Review by Raemy92 — APPROVED** [review]
ship it!

**Pull request merged**
